// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnlBU1-0FuZRqT9OimNwDmnM5ca7q1Z3I',
    appId: '1:958131599258:web:e61ede8971f9800a07ec23',
    messagingSenderId: '958131599258',
    projectId: 'customer-73870',
    authDomain: 'customer-73870.firebaseapp.com',
    databaseURL: 'https://customer-73870-default-rtdb.firebaseio.com',
    storageBucket: 'customer-73870.appspot.com',
    measurementId: 'G-T63PQ3FZFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrfFBjZShIAXMqvdt0MqvhKMhyIEqC3Bs',
    appId: '1:958131599258:android:c14b71de3f8fb3e607ec23',
    messagingSenderId: '958131599258',
    projectId: 'customer-73870',
    databaseURL: 'https://customer-73870-default-rtdb.firebaseio.com',
    storageBucket: 'customer-73870.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5vZUcfREj-iOlTTDXUVHX4EjXBn1HZv0',
    appId: '1:958131599258:ios:4fc3a2ca30df4ea807ec23',
    messagingSenderId: '958131599258',
    projectId: 'customer-73870',
    databaseURL: 'https://customer-73870-default-rtdb.firebaseio.com',
    storageBucket: 'customer-73870.appspot.com',
    iosBundleId: 'com.digigrow.urride.ios',
  );
}
